create table users
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(255) not null,
    email    varchar(255) not null,
    password varchar(255) not null
);

alter table users
    owner to postgres;
